### PR TITLE
support packet-switched flows visualization

### PR DESCRIPTION
**Pull request by Yu-Zhewen**

### CODE REVIEW

**Comment by andrej** [comment]
The compiler no longer compiles for me after this change due to unused variable `dstTile` due to the moved `#ifndef NDEBUG`.

```
[59/439] Building CXX object lib/Dialect/AIE/Transforms/CMakeFiles/obj.AIETransforms.dir/AIECreatePathFindFlows.cpp.o
FAILED: lib/Dialect/AIE/Transforms/CMakeFiles/obj.AIETransforms.dir/AIECreatePathFindFlows.cpp.o 
/usr/bin/c++ -DGTEST_HAS_RTTI=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/andre/mlir-aie/llvm/llvm/include -I/home/andre/mlir-aie/llvm/build/include -I/home/andre/mlir-aie/llvm/mlir/include -I/home/andre/mlir-aie/llvm/build/tools/mlir/include -I/home/andre/mlir-aie/include -I/home/andre/mlir-aie/build/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=sign-compare -Werror=unused -Werror=return-type -Werror=mismatched-tags -O3 -DNDEBUG -std=gnu++17 -fvisibility=hidden -fvisibility-inlines-hidden   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -funwind-tables -fno-rtti -MD -MT lib/Dialect/AIE/Transforms/CMakeFiles/obj.AIETransforms.dir/AIECreatePathFindFlows.cpp.o -MF lib/Dialect/AIE/Transforms/CMakeFiles/obj.AIETransforms.dir/AIECreatePathFindFlows.cpp.o.d -o lib/Dialect/AIE/Transforms/CMakeFiles/obj.AIETransforms.dir/AIECreatePathFindFlows.cpp.o -c /home/andre/mlir-aie/lib/Dialect/AIE/Transforms/AIECreatePathFindFlows.cpp
/home/andre/mlir-aie/lib/Dialect/AIE/Transforms/AIECreatePathFindFlows.cpp: In member function ‘virtual void {anonymous}::ConvertFlowsToInterconnect::rewrite(xilinx::AIE::FlowOp, mlir::OpConversionPattern<xilinx::AIE::FlowOp>::OpAdaptor, mlir::ConversionPatternRewriter&) const’:
/home/andre/mlir-aie/lib/Dialect/AIE/Transforms/AIECreatePathFindFlows.cpp:78:10: error: variable ‘dstTile’ set but not used [-Werror=unused-but-set-variable]
   78 |     auto dstTile = cast<TileOp>(flowOp.getDest().getDefiningOp());
      |          ^~~~~~~
/home/andre/mlir-aie/lib/Dialect/AIE/Transforms/AIECreatePathFindFlows.cpp:79:10: error: unused variable ‘dstBundle’ [-Werror=unused-variable]
   79 |     auto dstBundle = flowOp.getDestBundle();
      |          ^~~~~~~~~
/home/andre/mlir-aie/lib/Dialect/AIE/Transforms/AIECreatePathFindFlows.cpp:80:10: error: unused variable ‘dstChannel’ [-Werror=unused-variable]
   80 |     auto dstChannel = flowOp.getDestChannel();
      |          ^~~~~~~~~~
```

**Comment by andrej** [comment]
It was an easy fix, please see #1582.

**Comment by erwei-xilinx** [comment]
> It was an easy fix, please see #1582.

Thanks for fixing the issue, @andrej !

**Comment by andrej** [comment]
No problem. With your blessing, I will merge it as soon as the tests pass?

**Comment by erwei-xilinx** [comment]
> No problem. With your blessing, I will merge it as soon as the tests pass?

Sounds good to me. I enabled "Merge when ready".

**Comment by andrej** [comment]
Thank you!

**Pull request merged**
