### PR TITLE
Fix ipu_sync for multicore in matrix vector ref design

### PR DESCRIPTION
**Pull request by jtuyls**
@jgmelber In the multicore matrix vector reference design, I believe every shim connection requires its own sync to make sure all output data is properly returned?

### CODE REVIEW

**Review by jgmelber — APPROVED** [review]
Thanks for fixing the sync! I would like to keep the matrix size as 288x288 (matches the weights size for Llama2 tinystories15M weights

**Comment by jtuyls** [comment]
> Thanks for fixing the sync! I would like to keep the matrix size as 288x288 (matches the weights size for Llama2 tinystories15M weights

Ok, but then 

> Thanks for fixing the sync! I would like to keep the matrix size as 288x288 (matches the weights size for Llama2 tinystories15M weights

Ok! Is updating to 3 cores ok, or should it be 1?

**Comment by jtuyls** [comment]
> > > Thanks for fixing the sync! I would like to keep the matrix size as 288x288 (matches the weights size for Llama2 tinystories15M weights
> > 
> > 
> > Ok! Is updating to 3 cores ok, or should it be 1?
> 
> I'd recommend 1, 2 or 4, it divides the work evenly

288 / 32 = 9, which is not divisible by 2/4 and I believe this failed. I set the number of cores to 1 now.

**Comment by jtuyls** [comment]
@jgmelber CI has passed with a latest formatting fix. If it looks good, I think we can merge?

**Comment by jgmelber** [comment]
> @jgmelber CI has passed with a latest formatting fix. If it looks good, I think we can merge?

Yes, LGTM

**Pull request merged**
