### PR TITLE
Modify multi-col aie_partition.json

### PR DESCRIPTION
**Pull request by erwei-xilinx**
Fixes issue https://github.com/Xilinx/mlir-aie/issues/1159

### CODE REVIEW

**Review by stephenneuendorffer — APPROVED** [review]

**Comment by jgmelber** [comment]
I'm not sure this is a good change and limits the number of independent applications/processes that can use a device if we always build 4 column designs

**Comment by jgmelber** [comment]
> I'm not sure this is a good change and limits the number of independent applications/processes that can use a device if we always build 4 column designs

Just to add, a desirable approach to application implementation could use multiple kernels within an XCLBIN or multiple XCLBINs for different functions (ie. GEMMs, Activations, various sizes).

**Comment by erwei-xilinx** [comment]
> Just to add, a desirable approach to application implementation could use multiple kernels within an XCLBIN or multiple XCLBINs for different functions (ie. GEMMs, Activations, various sizes).

I agree. This PR is intended to do a short term fix where IREE-AMD-AIE will fail with any design using more than one AIE column, therefore blocking IREE dev progress. A long-term approach would be what you described here.

**Comment by jgmelber** [comment]
> > Just to add, a desirable approach to application implementation could use multiple kernels within an XCLBIN or multiple XCLBINs for different functions (ie. GEMMs, Activations, various sizes).
> 
> I agree. This PR is intended to do a short term fix where IREE-AMD-AIE will fail with any design using more than one AIE column, therefore blocking IREE dev progress. A long-term approach would be what you described here.

What is the failure? If the design uses a tile in every column, then the metadata will enable 4 columns

**Comment by erwei-xilinx** [comment]
> What is the failure? If the design uses a tile in every column, then the metadata will enable 4 columns

I created an issue on this: https://github.com/Xilinx/mlir-aie/issues/1159 Here is a gist summarizing how to reproduce the issue: https://gist.github.com/erwei-xilinx/f3d7ead1e9faad31fbf0d4ff7f82b18c

**Pull request merged**
