### PR TITLE
Fixing dynamic objectFifo 

### PR DESCRIPTION
**Pull request by pvasireddy-amd**
Issue #1884

### CODE REVIEW

**Comment by pvasireddy-amd** [comment]
The sliding_window_conditional example is the only one that fails, but this issue appears unrelated to dynamic objectFifos. The example defines 3 input objectFifos, but only 2 are created when lowered using the --aie-objectFifo-stateful-transform pass. Currently still investigating.

**Comment by pvasireddy-amd** [comment]
Since the problem is unrelated to the dynamic objectFifos, I have pushed a working MLIR version of the `sliding_window_conditional` example into `test/npu-xrt/dynamic_object_fifo/sliding_window_conditional`. A separate PR will follow with the necessary fixes to enable running the Python version of this example.

**Review by AndraBisca — APPROVED** [review]
Thank you for the fix!
Regarding the sliding_window_conditional example, it appears that the if-statement does not lower from IRON to MLIR as there is no wrapper similar to the for_ loop statement. As we plan to add this change in a subsequent PR I am happy to merge this fix in already.

**Review by jgmelber — APPROVED** [review]

**Comment by hunhoffe** [comment]
For the record, mlir-python-extras should contain some wrappers for if statements e.g., here: https://github.com/makslevental/mlir-python-extras/blob/b19f9b4246a0e092a2f30eaa6dde8584adb64bc5/mlir/extras/dialects/ext/scf.py#L363

I have not attempted to use them in IRON, but wanted to mention them for whoever goes down that path later on!

**Pull request merged**
