### PR TITLE
bump llvm

### PR DESCRIPTION
**Pull request by fifield**
update llvm to 1cde124
account for [expand_shape changes](https://github.com/llvm/llvm-project/commit/97069a86193a617a9e4cf742a29db6116b2bf449)

### CODE REVIEW

**Comment by jsetoain** [comment]
Yes, I was going to say. Between the version I originally used to replicate the other issues and the latest one, another change broke another test 😬

**Review by jsetoain — APPROVED** [review]

**Comment by jsetoain** [comment]
> Yes, I was going to say. Between the version I originally used to replicate the other issues and the latest one, another change broke another test 😬

@makslevental It looks like we're not running the integration tests any more (the ones activated with `-DAIE_INCLUDE_INTEGRATION_TESTS=ON`), that's why CI didn't catch the issues.

**Comment by fifield** [comment]
> > Yes, I was going to say. Between the version I originally used to replicate the other issues and the latest one, another change broke another test 😬
> 
> @makslevental It looks like we're not running the integration tests any more (the ones activated with `-DAIE_INCLUDE_INTEGRATION_TESTS=ON`), that's why CI didn't catch the issues.

It looks like I wasn't running those tests either. I get a few failures after turning them on.

**Comment by jsetoain** [comment]
> > > Yes, I was going to say. Between the version I originally used to replicate the other issues and the latest one, another change broke another test 😬
> > 
> > 
> > @makslevental It looks like we're not running the integration tests any more (the ones activated with `-DAIE_INCLUDE_INTEGRATION_TESTS=ON`), that's why CI didn't catch the issues.
> 
> It looks like I wasn't running those tests either. I get a few failures after turning them on.

The same happened to me due to recent dev. env shenanigans. Anyway, the patch I sneaked right before this one fixes those issues, but it looks like after rebase a test failed. I suspect it was one of those spurious failures we're getting later because the previous run finished successfully, might be worth looking into it.

**Pull request merged**
