### PR TITLE
[vck5000-dynamic-dma-config] more test cleanups

### PR DESCRIPTION
**Pull request by fifield**
Follow up to https://github.com/Xilinx/mlir-aie/pull/1124 for the other tests. These 3 now pass for me on vck5000 without the makefiles:
reference_designs/dynamic_dma_config_add_one
reference_designs/dynamic_dma_config_add_one_kernel
reference_designs/dynamic_dma_config_add_one_kernel_obj_fifo

### CODE REVIEW

**Comment by fifield** [comment]
```
Failed Tests (1):
  AIE_REFERENCE_DESIGNS :: ipu-xrt/add_one_objFifo_no_mem_tile/run.lit

**Comment by eddierichter-amd** [comment]
> ```
> Failed Tests (1):
>   AIE_REFERENCE_DESIGNS :: ipu-xrt/add_one_objFifo_no_mem_tile/run.lit
> ```

This is failing on VCK5000 or IPU?

**Comment by fifield** [comment]
> > ```
> > Failed Tests (1):
> >   AIE_REFERENCE_DESIGNS :: ipu-xrt/add_one_objFifo_no_mem_tile/run.lit
> > ```
> 
> This is failing on VCK5000 or IPU?

It's failing on ipu,
https://github.com/Xilinx/mlir-aie/actions/runs/8270947534/job/22629627157?pr=1127#step:3:3221

the device is wrong?
https://github.com/Xilinx/mlir-aie/compare/main...vck5000-dynamic-dma-config#diff-a53692a0d05900406cd880cb61c1ffc58c1188b467ade833cf77676fd738acaaR18

**Comment by eddierichter-amd** [comment]
> > > ```
> > > Failed Tests (1):
> > >   AIE_REFERENCE_DESIGNS :: ipu-xrt/add_one_objFifo_no_mem_tile/run.lit
> > > ```
> > 
> > 
> > This is failing on VCK5000 or IPU?
> 
> It's failing on ipu, https://github.com/Xilinx/mlir-aie/actions/runs/8270947534/job/22629627157?pr=1127#step:3:3221
> 
> the device is wrong? [main...vck5000-dynamic-dma-config#diff-a53692a0d05900406cd880cb61c1ffc58c1188b467ade833cf77676fd738acaaR18](https://github.com/Xilinx/mlir-aie/compare/main...vck5000-dynamic-dma-config#diff-a53692a0d05900406cd880cb61c1ffc58c1188b467ade833cf77676fd738acaaR18)

Yeah, I had this targeting the VCK5000 so the device and the columns are different. I get this is the ipu-xrt directory so I can change that.

**Pull request merged**
