### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by fifield**
try https to fix workflow error

e.g.
https://github.com/Xilinx/mlir-aie/actions/runs/7922071274/job/21628813529#step:4:1899
https://github.com/Xilinx/mlir-air/actions/runs/7926008709/job/21640115581?pr=424#step:13:43

### CODE REVIEW

**Comment by makslevental** [comment]
This is most likely a temporary (flaky) fail on github's side? Don't think it's solvable?

**Comment by fifield** [comment]
> This is most likely a temporary (flaky) fail on github's side? Don't think it's solvable?

I think I've managed to improve it https://github.com/Xilinx/mlir-aie/actions/runs/7926308852/job/21640901724  At least it didn't die on submodule checkout

**Comment by fifield** [comment]
and it's a different error:
```
  In file included from /mlir-aie/third_party/bootgen/authentication.cpp:27:
  /mlir-aie/third_party/bootgen/authentication.h:33:10: fatal error: openssl/bn.h: No such file or directory
     33 | #include <openssl/bn.h>
        |          ^~~~~~~~~~~~~~
```
@stephenneuendorffer

**Comment by fifield** [comment]
> and it's a different error:
> 
> ```
>   In file included from /mlir-aie/third_party/bootgen/authentication.cpp:27:
>   /mlir-aie/third_party/bootgen/authentication.h:33:10: fatal error: openssl/bn.h: No such file or directory
>      33 | #include <openssl/bn.h>
>         |          ^~~~~~~~~~~~~~
> ```
> 
> @stephenneuendorffer

I guess we need openssl libs on that docker image?

**Comment by stephenneuendorffer** [comment]
> I guess we need openssl libs on that docker image?

Yup.. but I'm not sure why it didn't fail for me before?

**Review by stephenneuendorffer — APPROVED** [review]

**Pull request merged**
