### PR TITLE
[fix] remove openssl::applink target

### PR DESCRIPTION
**Pull request by makslevental**

### CODE REVIEW

**Comment by andrej** [comment]
Heads up, with this change, trying to compile `reference_designs/ipu-xrt/matrix_multiplication` this gives me a segmentation fault in `bootgen`:

```
bootgen -arch versal -image /home/andre/mlir-aie/reference_designs/ipu-xrt/matrix_multiplication/build/aie.mlir.prj/design.bif -o /home/andre/mlir-aie/reference_designs/ipu-xrt/matrix_multiplication/build/aie.mlir.prj/design.pdi -w
Segmentation fault (core dumped)
```

I accidentally installed the wheel as of this commit instead of main, and just wanted to let you know I stumbled across this. So this is probably not ready for `main` yet.

**Comment by makslevental** [comment]
> Heads up, with this change, trying to compile `reference_designs/ipu-xrt/matrix_multiplication` this gives me a segmentation fault in `bootgen`:
> 
> ```
> bootgen -arch versal -image /home/andre/mlir-aie/reference_designs/ipu-xrt/matrix_multiplication/build/aie.mlir.prj/design.bif -o /home/andre/mlir-aie/reference_designs/ipu-xrt/matrix_multiplication/build/aie.mlir.prj/design.pdi -w
> Segmentation fault (core dumped)
> ```
> 
> I accidentally installed the wheel as of this commit instead of main, and just wanted to let you know I stumbled across this. So this is probably not ready for `main` yet.

God bless you for catching that because I was about to land

**Comment by makslevental** [comment]
can't block my own PR so I'm converting to draft until we can figure this out thoroughly

**Comment by andrej** [comment]
Please double check if you can reproduce the error. It might be that I just did something wrong on my end.

**Pull request closed without merging**
