### PR TITLE
Matrix Multiplication Improvements

### PR DESCRIPTION
**Pull request by andrej**
- work around object fifo bug #1547 
- in host verification code, accumulate in float instead of bf16 -- this allows verification to pass even for bigger problem sizes, where before the accumulation errors got too big
- if problem size is beyond threshold, stochastically verify instead of exhaustively  (exhaustively verifying takes way too long, which is probably why the failed verification for larger problem sizes went undetected before) -- if this is merged, we can close #1134 which contains a similar change
- add assertions and comments
- improve verification output
- add workaround comment for excessive program size (CDO generation error `[AIE ERROR] _XAie_LoadProgMemSection():230: Overflow of program memory` e.g. for size M=768 K=768 N=256 if `fifo_depth>1`)

cc @jgmelber

### CODE REVIEW

**Comment by andrej** [comment]
- make use of changes in #1538 to simplify code (strides) for whole_array design
- allow changing inner tile size (small m, k, n) for whole_array design
- replace complicated verficiation code with the naive implementation; the idea was that the other implementation would be faster, but it was not (significantly); swapped the naive version back in to have easier maintainability and confidence in the code

**Comment by andrej** [comment]
@jgmelber Kindly kick off the tests for this when you get a chance. I fixed a number of issues with the matmuls that slid by because the verification tolerance was a bit high. I reduced the tolerance, so let's see if the tests reveal more issues.

**Review by fifield — APPROVED** [review]

**Comment by jgmelber** [comment]
@andrej matrix_vector still needs to be fixed, the rest look okay

**Comment by andrej** [comment]
@jgmelber Hopefully this will pass now

**Comment by andrej** [comment]
@jgmelber Could you kick off the tests on this please?

**Comment by andrej** [comment]
Looks like tests pass but I forgot to format. Another try please @jgmelber ?

**Pull request merged**
