### PR TITLE
[AMD-AIE] Update the microkernel to be targeted by Pad-Pack pipeline

### PR DESCRIPTION
**Pull request by Abhishek-Varma**
-- This commit updates the microkernel to be targeted by Pad-Pack
   pipeline.

Signed-off-by: Abhishek Varma <abhvarma@amd.com>

NOTE: We are removing the `matmul_scalar_*_*` version since it was a non-performant microkernel and was targeted by Pad pipeline which will be deprecated.

### CODE REVIEW

**Review by nirvedhmeshram — APPROVED** [review]
LGTM!

**Comment by fifield** [comment]
> Failures seem unrelated to me "Update gcc" :-
> 
> ```
> Err:1 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 libgcc-s1 amd64 13.1.0-8ubuntu1~20.04.2
>   503  Service Unavailable [IP: 185.125.190.80 80]
> ```
> 
> I've just modified the kernel file - and it didn't even make it to the "build".
> 
> Can someone please take a look?

This was an outage of the PPA repository. I reran the checks and they are now passing.

**Comment by nirvedhmeshram** [comment]
@Abhishek-Varma do you want to update the branch and merge if the tests pass thyen?

**Comment by Abhishek-Varma** [comment]
> @Abhishek-Varma do you want to update the branch and merge if the tests pass then?

Thanks @nirvedhmeshram - yes, we can go ahead with merging this branch.

There'd be one more update required but that'll be probably be adding of zero-filling ukernel - I'll raise another PR for it next week.

**Pull request merged**
