### PR TITLE
Offset calculation should be purely based on offsets and strides

### PR DESCRIPTION
**Pull request by erwei-xilinx**
… not memref shape.

### CODE REVIEW

**Comment by fifield** [comment]
Do you have a test to show the incorrect/fixed behavior?

**Review by andrej — APPROVED** [review]
I agree that this makes more sense. I think a lot of examples (all of them, since you did not have to update any?) just use the lowest-dimension offset so did not have to worry about this inconsistency. However maybe @jgmelber has thoughts as well?

**Comment by erwei-xilinx** [comment]
> Do you have a test to show the incorrect/fixed behavior?

Yeah I have an example driven from AIR. Let me make a test to show the fixed behavior.

**Comment by erwei-xilinx** [comment]
> I agree that this makes more sense. I think a lot of examples (all of them, since you did not have to update any?) just use the lowest-dimension offset so did not have to worry about this inconsistency. However maybe @jgmelber has thoughts as well?

Yeah I think you are right. Existing examples in both AIR and AIE never really triggered the highest wrap-and-stride offset dimensions, until when I recently was debugging a batch matmul from AIR.

**Comment by erwei-xilinx** [comment]
> Do you have a test to show the incorrect/fixed behavior?

Test added.

**Pull request merged**
