### PR TITLE
Don't use opaque pointers in aiecc.py

### PR DESCRIPTION
**Pull request by makslevental**
fixes https://github.com/Xilinx/mlir-aie/issues/640 assuming the appropriate patch has been applied to upstream LLVM.

### CODE REVIEW

**Comment by cabreraam** [comment]
After checking out the `opaque_ptrs_aiecc` branch and performing a fresh build of `llvm` and `mlir-aie`, I still can't get the first tutorial to build, though I error out at an `aie-opt` step, not `aie-translate`. So maybe that's progress? Should I be doing something different?

```bash
$ make
aiecc.py -j4 aie.mlir
Found Vitis at /auto/software/swtree/ubuntu22.04/x86_64/Xilinx/Vitis/2023.1
 MLIR compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 Worker<Pass-Options-Parser>: no such option "use-opaque-pointers
Error encountered while running: aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm="use-opaque-pointers=0" --convert-arith-to-llvm="use-opaque-pointers=0" --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir
 Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 Worker
make: *** [Makefile:14: core_1_4.elf] Error 1
```

**Comment by makslevental** [comment]
@cabreraam my bad I got a little overzealous and add that option to `convert-math-to-llvm` and `convert-arith-to-llvm` which indeed don't support that anymore. I just pushed up the change that removes - can you try again?

**Comment by cabreraam** [comment]
Unfortunately, still running into an error:

```bash
(mlir-aie) 93u@intrepid /noback/93u/Research/intrepid/mlir-aie/tutorials/tutorial-1 (opaque_ptrs_aiecc)
$ make
aiecc.py -j4 aie.mlir
Found Vitis at /auto/software/swtree/ubuntu22.04/x86_64/Xilinx/Vitis/2023.1
 MLIR compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 Worker<Pass-Options-Parser>: no such option "use-opaque-pointers
Error encountered while running: aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm --convert-arith-to-llvm --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir
 Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 Worker
make: *** [Makefile:14: core_1_4.elf] Error 1
```

Here is the before and after commit `da96206` calls to `aie-opt`


```
Before `da96206`:
aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm="use-opaque-pointers=0" --convert-arith-to-llvm="use-opaque-pointers=0" --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir

After `da96206 `:
aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm --convert-arith-to-llvm --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir
```

**Comment by makslevental** [comment]
@cabreraam can you repeat with `-v`? Also btw are you on the LLVM discord? my handle is the same if you want to ping me (so we can debug in real time).

**Comment by cabreraam** [comment]
I'm not active on Discord but I'll try to hop on. In the mean time, here's `-v`:
```
$ make
aiecc.py -v -j4 aie.mlir
Found Vitis at /auto/software/swtree/ubuntu22.04/x86_64/Xilinx/Vitis/2023.1

compiling aie.mlir
created temporary directory aie.mlir.prj
 MLIR compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00 0/1 1 Workeraie-opt --lower-affine --aie-canonicalize-device --aie-assign-lock-ids --aie-register-objectFifos --aie-objectFifo-stateful-transform --aie-lower-broadcast-packet --aie-create-packet-flows --aie-lower-multicast --aie-assign-buffer-addresses -convert-scf-to-cf aie.mlir -o aie.mlir.prj/input_with_addresses.mlir
Done in 0.041 sec: aie-opt --lower-affine --aie-canonicalize-device --aie-assign-lock-ids --aie-register-objectFifos --aie-objectFifo-stateful-transform --aie-lower-broadcast-packet --aie-create-packet-flows --aie-lower-multicast --aie-assign-buffer-addresses -convert-scf-to-cf aie.mlir -o aie.mlir.prj/input_with_addresses.mlir
aie-translate --aie-generate-corelist aie.mlir.prj/input_with_addresses.mlir
aie-translate --aie-generate-target-arch aie.mlir.prj/input_with_addresses.mlir
xchesscc_wrapper aie +w aie.mlir.prj/work -c -d -f +f +P 4 /noback/93u/Research/intrepid/mlir-aie/install/aie_runtime_lib/AIE/chess_intrinsic_wrapper.cpp -o aie.mlir.prj/chess_intrinsic_wrapper.ll
 MLIR compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 WorkerDone in 3.342 sec: xchesscc_wrapper aie +w aie.mlir.prj/work -c -d -f +f +P 4 /noback/93u/Research/intrepid/mlir-aie/install/aie_runtime_lib/AIE/chess_intrinsic_wrapper.cpp -o aie.mlir.prj/chess_intrinsic_wrapper.ll
sed -i s/^target.*// aie.mlir.prj/chess_intrinsic_wrapper.ll
Done in 0.019 sec: sed -i s/^target.*// aie.mlir.prj/chess_intrinsic_wrapper.ll
sed -i s/noalias_sidechannel[^,]*,// aie.mlir.prj/chess_intrinsic_wrapper.ll
Done in 0.016 sec: sed -i s/noalias_sidechannel[^,]*,// aie.mlir.prj/chess_intrinsic_wrapper.ll
sed -i s/nocallback[^,]*,// aie.mlir.prj/chess_intrinsic_wrapper.ll
Done in 0.017 sec: sed -i s/nocallback[^,]*,// aie.mlir.prj/chess_intrinsic_wrapper.ll
aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm --convert-arith-to-llvm --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir
 MLIR compilation: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 Worker<Pass-Options-Parser>: no such option "use-opaque-pointers
Done in 0.046 sec: aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm --convert-arith-to-llvm --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir
Error encountered while running: aie-opt --aie-localize-locks --aie-standard-lowering --aie-normalize-address-spaces --canonicalize --cse --convert-vector-to-llvm="use-opaque-pointers=0" --expand-strided-metadata --lower-affine --convert-math-to-llvm --convert-arith-to-llvm --finalize-memref-to-llvm="use-opaque-pointers=0" --convert-func-to-llvm="use-opaque-pointers=0 use-bare-ptr-memref-call-conv=1" --convert-cf-to-llvm="use-opaque-pointers=0" --canonicalize --cse aie.mlir.prj/input_with_addresses.mlir -o aie.mlir.prj/input_opt_with_addresses.mlir
 Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:03 0/1 1 Worker
make: *** [Makefile:14: core_1_4.elf] Error 1
```

**Comment by makslevental** [comment]
@cabreraam okay guess I have to roll up my sleeves; 

image

so let me get back to you tomorrow-ish.

**Comment by makslevental** [comment]
@cabreraam try it now (I was using the pass args syntax incorrectly).

TODO: change aiecc.main to use a pass pipeline instead of individual pass args.

**Comment by makslevental** [comment]
@fifield I guess this still isn't complete. My patch is based off of your patch https://github.com/llvm/llvm-project/compare/main...fifield:llvm-project:llvm-b126ee6, which you IIRC you communicating should work. But even just applying your patch straight up, while I do get vaguely correct looking mlir (for tutorial 1):

```mlir
  llvm.func @core_1_4() {
    %0 = llvm.mlir.constant(31 : index) : i64
    %1 = llvm.mlir.constant(0 : index) : i64
    %2 = llvm.mlir.constant(14 : i32) : i32
    %3 = llvm.mlir.addressof @a14 : !llvm.ptr<array<256 x i32>>
    %4 = llvm.getelementptr %3[0, 0] : (!llvm.ptr<array<256 x i32>>) -> !llvm.ptr<i32>
    %5 = llvm.ptrtoint %4 : !llvm.ptr<i32> to i64
    %6 = llvm.and %5, %0  : i64
    %7 = llvm.icmp "eq" %6, %1 : i64
    "llvm.intr.assume"(%7) : (i1) -> ()
    %8 = llvm.getelementptr %4[3] : (!llvm.ptr<i32>) -> !llvm.ptr<i32>
    llvm.store %2, %8 : !llvm.ptr<i32>
    llvm.return
  }
```

i.e., no opaque pointers. But the ll to be passed to chess still has opaque pointers:

```llvm
define void @core_1_4() {
  %1 = and i64 ptrtoint (ptr @a14 to i64), 31
  %2 = icmp eq i64 %1, 0
  call void @llvm.assume(i1 %2)
  store i32 14, ptr getelementptr (i32, ptr @a14, i32 3), align 4
  ret void
}
```

**Comment by makslevental** [comment]
@cabreraam can you give it a shot now? I've also updated my distros @ mlir-wheels

**Comment by makslevental** [comment]
closing for the time being because https://github.com/Xilinx/mlir-aie/pull/656 reverts and fixes the issue.

**Pull request closed without merging**
