### PR TITLE
Allow f32 type in AIEX::IpuDmaMemcpyNdOp::verify()

### PR DESCRIPTION
**Pull request by nirvedhmeshram**
f32 type work with the current flow so no reason to fail them in the verifier.

### CODE REVIEW

**Review by makslevental — APPROVED** [review]
LGTM

**Comment by jgmelber** [comment]
LGTM. What is the case for using f32?

**Review by jgmelber — APPROVED** [review]

**Comment by nirvedhmeshram** [comment]
> LGTM. What is the case for using f32?

Do you mean test case within mlir-aie or more generally? I dont think there is a test case in the repo showing it but upstream models (coming from onxx/pytorch) have f32 types in them forvarious operators that use mlir-aie through iree-amd-aie.

**Comment by jgmelber** [comment]
> > LGTM. What is the case for using f32?
> 
> Do you mean test case within mlir-aie or more generally? I dont think there is a test case in the repo showing it but upstream models (coming from onxx/pytorch) have f32 types in them for various operators that use mlir-aie through iree-amd-aie.

Sounds good if it makes it easier to integrate. The OP matches the hardware where all lengths and strides occur at 4B boundaries so these have to be cast to I32 or F32.

**Comment by makslevental** [comment]
> Sounds good if it makes it easier to integrate. The OP matches the hardware where all lengths and strides occur at 4B boundaries so these have to be cast to I32 or F32.

Just to be a little pedantic - the stream width is 32b (4B) right? There's no notion of data type (signedness, floating point, etc.) right? So this op really should only be doing a `getMemref().getType().getElementTypeBitWidth() == 32` check right? @nirvedhmeshram can you actually make it so.

**Comment by nirvedhmeshram** [comment]
> > Sounds good if it makes it easier to integrate. The OP matches the hardware where all lengths and strides occur at 4B boundaries so these have to be cast to I32 or F32.
> 
> Just to be a little pedantic - the stream width is 32b (4B) right? There's no notion of data type (signedness, floating point, etc.) right? So this op really should only be doing a `getMemref().getType().getElementTypeBitWidth() == 32` check right? @nirvedhmeshram can you actually make it so.

Done. Btw @erieaton-amd is working on enabling bf16 through the flow which will need to relax this assumption further and add logic to pack the 4B boundary with two elements, @jgmelber @makslevental please let us know your thoughts and pointers for that.

**Comment by makslevental** [comment]
> Done. Btw @erieaton-amd is working on enabling bf16 through the flow which will need to relax this assumption further and add logic to pack the 4B boundary with two elements, @jgmelber @makslevental please let us know your thoughts and pointers for that.

Not an expert but I feel like the packing should happen _before_ this op rather than _in_ this op? Not sure.

**Comment by makslevental** [comment]
@nirvedhmeshram can you update the corresponding lowering here to also be purely in terms of bit width https://github.com/Xilinx/mlir-aie/blob/76427507e39e3d74d9a1ffdf092f47c195d38bea/lib/Dialect/AIEX/Transforms/AIEDmaToIpu.cpp#L249.

**Comment by nirvedhmeshram** [comment]
> Not an expert but I feel like the packing should happen _before_ this op rather than _in_ this op? Not sure.
It feels wrong to pack two bf16



> @nirvedhmeshram can you update the corresponding lowering here to also be purely in terms of bit width
> 
> https://github.com/Xilinx/mlir-aie/blob/76427507e39e3d74d9a1ffdf092f47c195d38bea/lib/Dialect/AIEX/Transforms/AIEDmaToIpu.cpp#L249
> 
> .

Done, so @makslevental it will be awkward to pack 2 bf16's in a f32 or 4 i8's into i32 before the ipuDmaMemcpyNdOp is created so I was thinking in the DmaToIpuPattern we can teach it to handle non 4B elements as a next step?

**Pull request merged**
