### PR TITLE
test strix runner

### PR DESCRIPTION
**Pull request by fifield**
enable amdhx370 runner

### CODE REVIEW

**Comment by fifield** [comment]
@jgmelber do we need `lit.cfg.py` updates in `test/npu-xrt` too ?
```
Failed Tests (40):
  AIE :: npu-xrt/add_12_i8_using_2d_dma_op_with_padding/run.lit
  AIE :: npu-xrt/add_21_i8_using_dma_op_with_padding/run.lit
  AIE :: npu-xrt/add_256_using_dma_op_no_double_buffering/run.lit
  AIE :: npu-xrt/add_314_using_dma_op/run.lit
  AIE :: npu-xrt/add_378_i32_using_dma_op_with_padding/run.lit
  AIE :: npu-xrt/add_blockwrite/run.lit
  AIE :: npu-xrt/add_maskwrite/run.lit
  AIE :: npu-xrt/add_one_ctrl_packet/run.lit
  AIE :: npu-xrt/add_one_ctrl_packet_4_cores/run.lit
  AIE :: npu-xrt/add_one_ctrl_packet_col_overlay/run.lit
  AIE :: npu-xrt/add_one_objFifo/run.lit
  AIE :: npu-xrt/add_one_two/run.lit
  AIE :: npu-xrt/add_one_two_txn/run.lit
  AIE :: npu-xrt/add_one_using_dma/run.lit
  AIE :: npu-xrt/adjacent_memtile_access/three_memtiles/aie2.py
  AIE :: npu-xrt/adjacent_memtile_access/two_memtiles/aie2.py
  AIE :: npu-xrt/cascade_flows/run.lit
  AIE :: npu-xrt/ctrl_packet_reconfig/run.lit
  AIE :: npu-xrt/ctrl_packet_reconfig_1x4_cores/run.lit
  AIE :: npu-xrt/ctrl_packet_reconfig_4x1_cores/run.lit
  AIE :: npu-xrt/dynamic_object_fifo/nested_loops/aie2.py
  AIE :: npu-xrt/dynamic_object_fifo/ping_pong/aie2.py
  AIE :: npu-xrt/dynamic_object_fifo/reduction/aie2.py
  AIE :: npu-xrt/matrix_multiplication_using_cascade/run.lit
  AIE :: npu-xrt/matrix_transpose/aie2.py
  AIE :: npu-xrt/memtile_dmas/blockwrite_using_locks/run.lit
  AIE :: npu-xrt/memtile_dmas/writebd/run.lit
  AIE :: npu-xrt/memtile_dmas/writebd_tokens/run.lit
  AIE :: npu-xrt/nd_memcpy_linear_repeat/aie2.py
  AIE :: npu-xrt/nd_memcpy_transforms/aie2.py
  AIE :: npu-xrt/neighbor_tile_memory_access/aie2.py
  AIE :: npu-xrt/packet_flow/run.lit
  AIE :: npu-xrt/packet_flow_fanin/run.lit
  AIE :: npu-xrt/packet_flow_fanout/run.lit
  AIE :: npu-xrt/sync_task_complete_token/aie2.py
  AIE :: npu-xrt/sync_task_complete_token_bd_chaining/aie2.py
  AIE :: npu-xrt/two_col/run.lit
  AIE :: npu-xrt/vec_vec_add_memtile_init/run.lit
  AIE :: npu-xrt/vec_vec_add_tile_init/run.lit
  AIE :: npu-xrt/vector_scalar_using_dma/run.lit
```

**Comment by jgmelber** [comment]
> @jgmelber do we need `lit.cfg.py` updates in `test/npu-xrt` too ?

We likely do, I have not pushed any

**Comment by jgmelber** [comment]
These are all failing because they are checking for "PASS!" in FileCheck rather than using the exit condition

**Comment by jgmelber** [comment]
These are `XFAIL` but pass when they do not run:
```
Unexpectedly Passed Tests (3):
  AIE :: npu-xrt/dynamic_object_fifo/sliding_window/aie2.py
  AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/aie2.py
  AIE :: npu-xrt/dynamic_object_fifo/two_core_sliding_window/aie2.py
```

**Comment by jgmelber** [comment]
This needs more verification that the host driver code (test.cpp, test.py, etc.) for all tests have correct return values after [3c35d74](https://github.com/Xilinx/mlir-aie/pull/1956/commits/3c35d7455ecdd2a4f01835d3e45bac1240a91d40).

**Comment by jgmelber** [comment]
```
********************
Failed Tests (1):
  AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/run.lit

********************
Unexpectedly Passed Tests (1):
  AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/aie2.py
```

I think these tests were modified or removed? @pvasireddy-amd @AndraBisca can you confirm?

**Comment by fifield** [comment]
> ```
> ********************
> Failed Tests (1):
>   AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/run.lit
> 
> ********************
> Unexpectedly Passed Tests (1):
>   AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/aie2.py
> ```
> 
> I think these tests were modified or removed? @pvasireddy-amd @AndraBisca can you confirm?

Yes, the failures were because I made a rebase mistake, I think they pass now.l

**Comment by AndraBisca** [comment]
> > ```
> > ********************
> > Failed Tests (1):
> >   AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/run.lit
> > 
> > ********************
> > Unexpectedly Passed Tests (1):
> >   AIE :: npu-xrt/dynamic_object_fifo/sliding_window_conditional/aie2.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think these tests were modified or removed? @pvasireddy-amd @AndraBisca can you confirm?
> 
> Yes, the failures were because I made a rebase mistake, I think they pass now.

The aie2.py file of the test was indeed removed and replaced with the aie.mlir (we will restore the IRON code in another PR). I can take a look Monday morning!

**Review by jgmelber — APPROVED** [review]

**Pull request merged**
