### PR TITLE
reorganize matrix multiplication reference designs

### PR DESCRIPTION
**Pull request by andrej**
Further reduce duplicated code in `reference_designs/ipu-xrt`.

In addition to better maintainability, this gives us:
- bugfixes and improvements in kernels apply to all designs (`single_column` got left behind before, for example)
- host code improvements and bugfixes shared between all designs

With these changes, we are also 90% of the way to having the sweep infrastructure in place for all designs. If we want to add traces for the other designs, all the host code for that is shared now so some work is saved there too.

I've tested that all designs still work locally. I will have to see if the CI still works too.

### CODE REVIEW

**Comment by jgmelber** [comment]
This is a good reorg. The kernels should move to: mlir-aie/aie_kernels though

**Comment by andrej** [comment]
Not sure why the test

```
Failed Tests (1):
  AIE :: ipu-xrt/matrix_multiplication_using_dma/run-a2x.lit
```

fails. This PR does not touch that test.

**Comment by fifield** [comment]
> Not sure why the test
> 
> ```
> Failed Tests (1):
>   AIE :: ipu-xrt/matrix_multiplication_using_dma/run-a2x.lit
> ```
> 
> fails. This PR does not touch that test.

I retriggered the checks and they are passing. `¯\_(ツ)_/¯`

**Comment by andrej** [comment]
Thank you Jeff. Unfortunately it got out of date with main so I rebased. Once the checks complete, feel free to merge @jgmelber.

**Pull request merged**
