### PR TITLE
TilerHelper and 2D Tiling Visualizations

### PR DESCRIPTION
**Pull request by hunhoffe**
## Description

This PR introduces some classes to help with data transformations/tiling and data visualization. The main classes introduced are:
* `TensorTile`: A class representing information for specifying a 'chunk' of data, suitable for use in describing a `npu_dma_memcpy_nd` operation; also includes code for visualizing the `TensorTile`.
* `TensorTileSequence`: A wrapper class for a list of `TensorTile`s; also includes code for visualization (including animations).
* `TensorTiler2D`: A class that helps with data tiling. Provides `simple_tiler()`, `group_tiler()`, and `step_tiler()` methods to aid in generating iterative patterns of tiling over the tensor.

I also include:
* A (non-exhaustive, but also not completely trivial) set of tests in `test/python/tensortiler`
* A minor edit of a few programming examples (`dma_transpose`, `matrix_scalar_add`, `row_wise_bias_add` `matrxi_multiplication/whole_array`) to show how to use the `TensorTiler2D`
* Two new programming examples (in `programming_examples/basic/tiling_exploration`) and an introductory notebook that use the device to create an access order map that can be compared to the map provided by the `TensorTiler2D`. These examples are meant to verify the `TensorTiler2D` can produce valid access patterns but also illustrate how to use the tensor tiling code.
* A change to `npu_dma_memcpy_nd` to support taking a `TensorTile` directly instead of sizes/strides/offset

Some incidental things that got included in this PR:
* First programming example with no inputs, only an output, which required some minor changes to support

## Note for future contributions
* Visualization of transformation chaining (e.g., toStream AND fromStream w/ ObjectFIFOLink)
* Helper class for transformation chaining?
* Support for overlapping data patterns (e.g., image transforms)
* Integration of visualization into runtime sequence and/or memtile data movement.

## Notes

Credit to Andre for his really excellent tool here: https://andreroesti.com/data-layout-viz/data_layout.html
This is my attempt at making something similar that can be integrated into a development tool directly, with the additional step of generating sizes/strides for you.

### CODE REVIEW

**Comment by fifield** [comment]
How hard is it to generalize from 2d?

**Comment by hunhoffe** [comment]
@fifield Great question but I'm not sure... This needs some work before it's ready for merge due to some complexities with translating between the sizes/strides generated by the TensorTiler2D and the limitations in form/sizes allowed by the hardware.

My plan right now is to get a bit more confident about the problem space in 2D (which is also easier to visualize) before moving on to something more complex.

**Comment by hunhoffe** [comment]
I believe this PR is ready to review. However, it contains two new notebooks so perhaps https://github.com/Xilinx/mlir-aie/pull/1909 should be merged first.

It also removes some tiling functions (which I believe are less featureful than what I've added). These functions are only used by unused examples, which may be removed entirely in a pending PR. So perhaps https://github.com/Xilinx/mlir-aie/pull/1908 should also be merged first.

**Comment by hunhoffe** [comment]
CI is currently failing because lit test for notebooks assumes dependencies which are only added in https://github.com/Xilinx/mlir-aie/pull/1909

**Review by jgmelber — APPROVED** [review]
One nitpick would be to add an overall README to the `tiling_exploration` programming example directory.

**Comment by hunhoffe** [comment]
Notes:
* Will have follow-on PR for better Python documentation (https://github.com/Xilinx/mlir-aie/issues/1923)
* Started follow-on PR for checking/benchmarking mat mul whole array implementation using tiler to generate sizes/strides (https://github.com/Xilinx/mlir-aie/pull/1924)

**Pull request merged**
