### PR TITLE
Use ubuntu-20.02 for clang-format

### PR DESCRIPTION
**Pull request by fifield**
clang-format-12 is no longer supported by ubuntu-latest https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

### CODE REVIEW

**Comment by stephenneuendorffer** [comment]
Unfortunately, 20.04 and 22.04 don't support clang-12 anymore.  I'd rather run the clang-tidy task under 20.04 than move to a clang-format that isn't available on our dev machines.  I do think we should start using clang-14 on 22.04, though.

**Review by stephenneuendorffer — CHANGES_REQUESTED** [review]
I'd rather just run this on 20.04, rather than ubuntu-latest

**Comment by fifield** [comment]
> I'd rather just run this on 20.04, rather than ubuntu-latest

I agree this is a safer approach for now since most users are on 20.04. I'll update the PR. But to answer your earlier question I think we should move to clang-14 (and 22.04+) across the board.

**Comment by stephenneuendorffer** [comment]
I'd agree, except that clang-14 isn't an one click install on 20.04...

**Pull request merged**
