### PR TITLE
single lock test

### PR DESCRIPTION
**Pull request by denolf**
formerly know as multi-rate, this is a focused test when only a single lock is used to synchronize host and AIE. Added AIE2 variant as well.

### CODE REVIEW

**Comment by stephenneuendorffer** [comment]
@AndraBisca @denolf This looks like a bug in LibXAIE.

LockAcquire eventually calls MaskPoll, because acquiring and releasing locks are actually implement using memory read operations.  The processor just polls until the memory location returns a 1.   MaskPoll looks like this:

```
	while (Count > 0U) {
		XAie_LinuxIO_Read32(IOInst, RegOff, &RegVal);
		if((RegVal & Mask) == Value) {
			Ret = XAIE_OK;
			break;
		}
		usleep(MinTimeOutUs);
		Count--;
	}

	/* Check for the break from timed-out loop */
	XAie_LinuxIO_Read32(IOInst, RegOff, &RegVal);
	if((Ret == XAIE_ERR) && ((RegVal & Mask) ==
			 Value)) {
		Ret = XAIE_OK;
	}

```
So basically rather than storing a variable to determine that the loop needs to exit, they just perform the (expensive) read again.  This works fine if reads are idempotent, but lock acquire/release are not.

**Comment by denolf** [comment]
@stephenneuendorffer thanks for looking into this. I am not sure I follow your remark. It seems no interrupt driven mechanism is implemented in libXAIE. As such, the expensive polling for the lock though `XAie_LinuxIO_Read32` needs to happen until the timeout value is reached. 
Or are you trying to say that the compiler might have optimized something away here?

**Comment by stephenneuendorffer** [comment]
The way that the lock is grabbed is solely through read operations.  You read the register, and if a bit is set, then you've acquired/released the lock.  The lock is released successfully in the loop, at which point it is possible that the AIE core completes its work and releases the lock.  The host then executes the final Read32 operation, releasing the lock a second time.

**Comment by stephenneuendorffer** [comment]
I patched this locally and got it to work.  Unfortunately, because of linux driver version issues, it seems challenging to pick up the latest version of aie-rt and use it with the current board image.

**Comment by denolf** [comment]
Got it now, thanks.
Upgrading to 2023.1 for both our board images and the Vitis tools (including aie-rt) should solve those conflicts.

**Review by AndraBisca — APPROVED** [review]
Looks good! Just one question: do we still want to keep the work around version as well if it will now work without it?

**Comment by denolf** [comment]
merged #468

**Pull request merged**
