### PR TITLE
fix cmakes

### PR DESCRIPTION
**Pull request by makslevental**
Not sure what the idea here is/was but having multiple reloads of everything (LLVM/MLIR/etc) resets CMake global properties like `MLIR_DIALECT_LIBS`, `MLIR_CONVERSION_LIBS`, etc..

### CODE REVIEW

**Review by fifield — APPROVED** [review]
I don't know the history either but the cleanup makes sense to me.

**Review by keryell — APPROVED** [review]
Great cleaning.

**Comment by stephenneuendorffer** [comment]
There's a specific point here: it enables configuring and running the tests against installed binaries.

**Review by stephenneuendorffer — CHANGES_REQUESTED** [review]
If you have a better idea how to accomplish running the tests independently, I'd love to hear it.

**Pull request closed without merging**
