### PR TITLE
update llvm

### PR DESCRIPTION
**Pull request by fifield**
update llvm to db1d8813

### CODE REVIEW

**Comment by fifield** [comment]
There are some issues with vector dialect in this update, possibly related to https://github.com/llvm/llvm-project/pull/97049.

example:
```
/home/runner/work/mlir-aie/mlir-aie/test/aievec/conv2d_msc_uij_i32_noinit.mlir:105:15: error: CHECK-NEXT: expected string not found in input
//CHECK-NEXT: vector.transfer_write %20, %arg2[%arg3, %arg4] {in_bounds = [true]} : vector<8xi32>, memref<2046x2046xi32>
              ^
<stdin>:37:67: note: scanning from here
 %20 = aievec.srs %19, %c0_i32 : vector<8xi80>, i32, vector<8xi32>
                                                                  ^
<stdin>:38:2: note: possible intended match here
 vector.transfer_write %20, %arg2[%arg3, %arg4] : vector<8xi32>, memref<2046x2046xi32>
 ^
```

@jsetoain @jamestcl-amd maybe you have some insights?

**Review by jsetoain — APPROVED** [review]
👍

**Comment by jsetoain** [comment]
I've updated all aievec tests that needed updating, plus removed the ones that require fixing the deprecated pass. There are a couple of integration tests (for TOSA) that require fixing as well, I'll work on those next.

**Comment by fifield** [comment]
Is passing CI but has the following tosa test failures as noted above:
```
Failed Tests (3):
  AIE :: Integration/Dialect/TOSA/i8xi8_mul_elem_16x1024_broadcast_1/i8xi8_mul_elem_2d_broadcast_1d_unit_dim.mlir
  AIE :: Integration/Dialect/TOSA/i8xi8_mul_elem_16x1024_broadcast_1/i8xi8_mul_elem_2d_broadcast_scalar.mlir
  AIE :: Integration/Dialect/TOSA/ui8_cast.mlir
```

**Comment by jsetoain** [comment]
> Is passing CI but has the following tosa test failures as noted above:
> 
> ```
> Failed Tests (3):
>   AIE :: Integration/Dialect/TOSA/i8xi8_mul_elem_16x1024_broadcast_1/i8xi8_mul_elem_2d_broadcast_1d_unit_dim.mlir
>   AIE :: Integration/Dialect/TOSA/i8xi8_mul_elem_16x1024_broadcast_1/i8xi8_mul_elem_2d_broadcast_scalar.mlir
>   AIE :: Integration/Dialect/TOSA/ui8_cast.mlir
> ```

I see these tests have been failing for a while, and for some reason are not being run in CI (I thought this had been solved already). I'm doing a bisection to try and locate the offending change, that should give us a hint.

**Pull request merged**
