### PR TITLE
add missing ipu example (sans for loop)

### PR DESCRIPTION
**Pull request by makslevental**
Note the `scf.for %arg3 = %c0 to %c8 step %c1` is commented out because the current (i.e., in main) implementation of `forLoop` doesn't support induction vars.

### CODE REVIEW

**Comment by jackl-xilinx** [comment]
The inner loop for the add_one example is still missing (see aie.mlir). @makslevental,  is this functionality is not possible?

**Comment by makslevental** [comment]
> The inner loop for the add_one example is still missing (see aie.mlir). @makslevental, is this functionality is not possible?

As the description states: not in main.

**Comment by makslevental** [comment]
You can find a fully functional implementation on the `python-bindings-cleanup-2` branch: https://github.com/Xilinx/mlir-aie/pull/754/commits/bc7295cf101706bf1243c0b79c6b7c5f98444744 .

**Review by jackl-xilinx — APPROVED** [review]
Good first step to add this design but we'll need the inner loop functionality to be supported that you have in the python-bindings-cleanup-2 branch.

**Pull request merged**
