### PR TITLE
Add LSP protocol server for AIE dialects

### PR DESCRIPTION
**Pull request by keryell**
This allows semantical features such as type information, auto-completion, etc. to IDE and editors using LSP.
See https://mlir.llvm.org/docs/Tools/MLIRLSP for use case.

To be used for example with Emacs:
```elisp
;; Enable MLIR mode
(require 'mlir-mode)
;; Prepare MLIR LSP mode
(load-file ".../llvm/mlir/utils/emacs/mlir-lsp-client.el")
(lsp-mlir-setup)
;; Think about customizing lsp-mlir-server-executable to use the server
;; with its own dialects.
; '(lsp-mlir-server-executable ".../mlir-aie/build/bin/aie-lsp-server")
;; Use lsp-mode in mlir-mode
(add-hook 'mlir-mode-hook 'lsp)
```

### CODE REVIEW

**Comment by keryell** [comment]
I need to add some tests.

**Comment by keryell** [comment]
@MaheshRavishankar as you are an Emacs user. :-)

**Review by fifield — CHANGES_REQUESTED** [review]
I tried it in vscode and it worked. The new files need copyright/license.

**Comment by keryell** [comment]
> I tried it in vscode and it worked. The new files need copyright/license.

Thanks for trying on your system.
Good catch for the copyright/license.

**Review by fifield — APPROVED** [review]

**Pull request merged**
