### PR TITLE
remove duplicate pass in aiecc

### PR DESCRIPTION
**Pull request by Yu-Zhewen**

### CODE REVIEW

**Comment by AndraBisca** [comment]
I'm not sure I see how these passes are duplicates. Could you please elaborate further on how the changes tie into each other?

**Comment by Yu-Zhewen** [comment]
I've noticed that both `aie-lower-broadcast-packet` and `aie-create-packet-flows` are being invoked twice in our current implementation—initially within `INPUT_WITH_SWITCHBOXES_PIPELINE` and secondly in `process_host_cgen`.

The current side effect is the packet routing happens way before circuit routing, which I believe is an undesirable behaviour since we may want to merge these two routing passes together in the furture?

After the change, both passes are only invoked once.

**Comment by Yu-Zhewen** [comment]
oh yes, updated now. Thanks!

**Review by AndraBisca — APPROVED** [review]
Looks good to me now!

**Pull request merged**
