### PR TITLE
Update docs for 6.8.8 kernel and latest xdna-driver

### PR DESCRIPTION
**Pull request by jgmelber**

### CODE REVIEW

**Comment by jgmelber** [comment]
I tested this locally with the previously failing vision programming examples and it passes.

**Review by fifield — APPROVED** [review]
I can also confirm that 6.8.8 + newest driver was passing all tests for me when I tried it ~3 days ago.

**Comment by keryell** [comment]
I need to make 6.8.9 since it is out.

**Review by keryell — APPROVED** [review]
Thanks.

**Comment by keryell** [comment]
I guess this merge queue concept is waiting for all the reviewers to do their due diligence..

**Pull request merged**
