### PR TITLE
Fix for polygeist tests following llvm bump.

### PR DESCRIPTION
**Pull request by david-vc**
Data layout attributes need to be changed from vector<2xi32> to vector<2xi64>.

### CODE REVIEW

**Comment by makslevental** [comment]
Hmm I thought I caught all of these.

**Comment by makslevental** [comment]
Hmm I thought I caught all of these.

**Comment by david-vc** [comment]
The build bot is not running these tests as they require chesscc.

**Comment by makslevental** [comment]
> The build bot is not running these tests as they require chesscc.

Yes but I had tested locally. Blame Vitis! Thanks for the fix!

**Comment by keryell** [comment]
I guess that these tests come from an old output from a Polygeist run?
Otherwise I am currently working on the integration of 'mlir-aie` into an LLVM mono with a modernized fork of Polygeist https://github.com/intel/llvm/tree/sycl-mlir/polygeist
I still have a lot of issues with 'mlir-aie` CMake configuration.

**Comment by david-vc** [comment]
Hi @keryell : Yes. the input MLIR was produced by polygeist more than 1/2 year ago.

**Pull request merged**
