### PR TITLE
rename remaining aie ops

### PR DESCRIPTION
**Pull request by makslevental**
This PR normalizes the remainder of the op names to match upstream convention (snake_case).

### CODE REVIEW

**Review by stephenneuendorffer — COMMENTED** [review]
This is a somewhat painful change, but it's probably better to do it sooner rather than later.

**Comment by makslevental** [comment]
> This is a somewhat painful change, but it's probably better to do it sooner rather than later.

FYI this change "simplifies" the python bindings in that we will no longer need to wrap miscased things there to achieve proper casing.

**Comment by keryell** [comment]
And there is the elephant in the room: `AIE` → `aie` :-)

**Comment by makslevental** [comment]
> And there is the elephant in the room: `AIE` → `aie` :-)

I would definitely like to make this change as well!

**Pull request merged**
