### PR TITLE
Dedicated build script for Ryzen AI

### PR DESCRIPTION
**Pull request by jgmelber**

### CODE REVIEW

**Review by keryell — APPROVED** [review]
It starts becoming complicated with all these scripts with a lot of code bloat.
We need to think to a way to reduce the technical debt.

**Comment by stephenneuendorffer** [comment]
I'm confused why there's a build-time difference here?

**Comment by jgmelber** [comment]
> I'm confused why there's a build-time difference here?

Building aie-rt from GitHub with sed change to two lines in the CDO backend file. Then passing that aie-rt with cmake to the build

**Review by denolf — APPROVED** [review]

**Comment by stephenneuendorffer** [comment]
> > I'm confused why there's a build-time difference here?
> 
> Building aie-rt from GitHub with sed change to two lines in the CDO backend file. Then passing that aie-rt with cmake to the build

That's scary...  If that's really different for different AIE targets, then needs to get pushed into aie-rt.

**Comment by jgmelber** [comment]
> > > I'm confused why there's a build-time difference here?
> > 
> > 
> > Building aie-rt from GitHub with sed change to two lines in the CDO backend file. Then passing that aie-rt with cmake to the build
> 
> That's scary... If that's really different for different AIE targets, then needs to get pushed into aie-rt.

Agreed. The number of different versions of aie-rt we have needs to be addressed.

**Comment by stephenneuendorffer** [comment]
> > > > I'm confused why there's a build-time difference here?
> > > 
> > > 
> > > Building aie-rt from GitHub with sed change to two lines in the CDO backend file. Then passing that aie-rt with cmake to the build
> > 
> > 
> > That's scary... If that's really different for different AIE targets, then needs to get pushed into aie-rt.
> 
> Agreed. The number of different versions of aie-rt we have needs to be addressed.

Then suggest you put a big FIXME around that :)

**Pull request merged**
